# Generated by Django 4.2.1 on 2023-05-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='name',
            new_name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'System_Admin'), (2, 'SYSTEM_STAFF'), (3, 'CLIENT_ADMIN'), (4, 'CLIENT_STAFF'), (5, 'CLIENT_CUSTOMERS')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ManyToManyField(to='users.restaurants'),
        ),
    ]
